import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Helper for dates in the past
function daysAgo(days, hours = 0) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hours);
  return d;
}

// 25 Failed Payment Scenarios
const failedPaymentsData = [
  {
    name: "Marcus Vance",
    email: "marcus.vance@vancetech.io",
    phone: "+1-415-555-0101",
    riskScore: 0.35,
    ltv: 4200.0,
    amount: 349.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INSUFFICIENT_FUNDS",
    code: "card_declined_insufficient_funds",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 3,
    notes: "Primary corporate Mastercard declined due to temporary cash balance. Follow-up dunning queued.",
  },
  {
    name: "Elena Rostova",
    email: "elena.rostova@cloudscale.net",
    phone: "+1-206-555-0142",
    riskScore: 0.15,
    ltv: 12500.0,
    amount: 890.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "EXPIRED_CARD",
    code: "card_expired",
    caseStatus: "IN_PROGRESS",
    priority: "URGENT",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 5,
    notes: "Executive card expired last month. Automated card updater notification sent.",
  },
  {
    name: "Liam O'Connor",
    email: "liam@celticdesigns.co.uk",
    phone: "+44-20-7946-0912",
    riskScore: 0.42,
    ltv: 2100.0,
    amount: 149.0,
    gateway: "ADYEN",
    method: "DEBIT_CARD",
    reason: "GENERIC_DECLINE",
    code: "do_not_honor",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Bank blocked international transaction. Customer contacted to approve fraud alert.",
  },
  {
    name: "Siddharth Menon",
    email: "siddharth@menonlogistics.in",
    phone: "+91-98200-55411",
    riskScore: 0.2,
    ltv: 8900.0,
    amount: 520.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INCORRECT_CVC",
    code: "incorrect_cvc",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 520.0,
    days: 12,
    notes: "Customer updated CVV code via self-serve link. Payment settled.",
  },
  {
    name: "Chloe Dubois",
    email: "chloe.dubois@atelier-paris.fr",
    phone: "+33-1-42-68-55-00",
    riskScore: 0.28,
    ltv: 3400.0,
    amount: 280.0,
    gateway: "BRAINTREE",
    method: "CREDIT_CARD",
    reason: "CARD_VELOCITY_EXCEEDED",
    code: "velocity_limit",
    caseStatus: "RECOVERED",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 280.0,
    days: 14,
    notes: "Smart retry executed 24h later after velocity window reset. Successfully processed.",
  },
  {
    name: "David K. Miller",
    email: "dmiller@millermedia.com",
    phone: "+1-312-555-0188",
    riskScore: 0.65,
    ltv: 1800.0,
    amount: 450.0,
    gateway: "STRIPE",
    method: "ACH",
    reason: "ACH_RETURN_R01",
    code: "insufficient_funds_ach",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 4,
    notes: "ACH direct debit returned with code R01. Customer notified to fund account.",
  },
  {
    name: "Amina Al-Mansoor",
    email: "amina@gulfventures.ae",
    phone: "+971-4-312-4455",
    riskScore: 0.18,
    ltv: 15400.0,
    amount: 1200.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "PROCESSING_ERROR",
    code: "issuer_unavailable",
    caseStatus: "RECOVERED",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 1200.0,
    days: 8,
    notes: "Issuer network outage during morning batch. Smart retry recovered full amount.",
  },
  {
    name: "Lucas Silva",
    email: "lucas.silva@inovacaobr.com",
    phone: "+55-11-98765-4321",
    riskScore: 0.52,
    ltv: 1600.0,
    amount: 95.0,
    gateway: "PADDLE",
    method: "CREDIT_CARD",
    reason: "FRAUD_SUSPECTED",
    code: "suspected_fraud_filter",
    caseStatus: "ESCALATED",
    priority: "URGENT",
    attempts: 3,
    recoveredAmount: 0.0,
    days: 6,
    notes: "Multiple decline attempts triggered fraud velocity heuristic. Assigned to manual compliance review.",
  },
  {
    name: "Rachel Greenstein",
    email: "rachel@apexadvisory.com",
    phone: "+1-646-555-0177",
    riskScore: 0.22,
    ltv: 6700.0,
    amount: 620.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CARD_DECLINED",
    code: "card_declined_generic",
    caseStatus: "IN_PROGRESS",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Dunning sequence Step 1 delivered and opened. Next automated retry scheduled.",
  },
  {
    name: "Hiroshi Tanaka",
    email: "tanaka.h@tokyodynamics.jp",
    phone: "+81-3-5555-0199",
    riskScore: 0.12,
    ltv: 18200.0,
    amount: 1450.0,
    gateway: "ADYEN",
    method: "CREDIT_CARD",
    reason: "EXPIRED_CARD",
    code: "card_expired",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "Corporate Visa expired end of quarter. Payment update link sent to accounts department.",
  },
  {
    name: "Klaus Weber",
    email: "k.weber@berlin-automotive.de",
    phone: "+49-30-1234567",
    riskScore: 0.38,
    ltv: 5100.0,
    amount: 410.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INSUFFICIENT_FUNDS",
    code: "insufficient_funds",
    caseStatus: "IN_PROGRESS",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 7,
    notes: "Second retry scheduled for payroll date. SMS notification dispatched.",
  },
  {
    name: "Sofia Morales",
    email: "sofia.m@andesmining.cl",
    phone: "+56-2-2345-6789",
    riskScore: 0.45,
    ltv: 3900.0,
    amount: 320.0,
    gateway: "BRAINTREE",
    method: "CREDIT_CARD",
    reason: "3DS_NOT_ENROLLED",
    code: "three_ds_not_enrolled",
    caseStatus: "OPEN",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 4,
    notes: "Card does not support 3DS protocol. Advised customer to switch to alternative payment method.",
  },
  {
    name: "Nathaniel Brooks",
    email: "nbrooks@brookscapital.com",
    phone: "+1-617-555-0133",
    riskScore: 0.19,
    ltv: 14000.0,
    amount: 980.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "LOST_OR_STOLEN_CARD",
    code: "stolen_card",
    caseStatus: "FAILED",
    priority: "HIGH",
    attempts: 3,
    recoveredAmount: 0.0,
    days: 20,
    notes: "Card reported stolen by issuing bank. Customer account flagged for card replacement.",
  },
  {
    name: "Grace Hopper LLC",
    email: "billing@hoppertech.io",
    phone: "+1-512-555-0155",
    riskScore: 0.25,
    ltv: 9200.0,
    amount: 750.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "LIMIT_EXCEEDED",
    code: "withdrawal_count_limit_exceeded",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 750.0,
    days: 9,
    notes: "Monthly credit limit reached. Customer cleared balance and payment completed on second retry.",
  },
  {
    name: "Oscar Lindqvist",
    email: "oscar@nordicfin.se",
    phone: "+46-8-123-4567",
    riskScore: 0.3,
    ltv: 4600.0,
    amount: 380.0,
    gateway: "ADYEN",
    method: "DEBIT_CARD",
    reason: "INSUFFICIENT_FUNDS",
    code: "insufficient_funds",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Account overdraft protection triggered. Reminder email sent.",
  },
  {
    name: "Priya Sharma",
    email: "priya.sharma@zenithanalytics.co",
    phone: "+1-408-555-0192",
    riskScore: 0.14,
    ltv: 11200.0,
    amount: 670.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CARD_DECLINED",
    code: "do_not_honor",
    caseStatus: "IN_PROGRESS",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 4,
    notes: "Fraud protection flag on new bank card. Customer verified identity with bank.",
  },
  {
    name: "Mateo Rossi",
    email: "mateo@milanomodastyle.it",
    phone: "+39-02-5555-8910",
    riskScore: 0.48,
    ltv: 2800.0,
    amount: 190.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INSUFFICIENT_FUNDS",
    code: "insufficient_funds",
    caseStatus: "OPEN",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 3,
    notes: "Initial decline. Standard 3-day dunning sequence activated.",
  },
  {
    name: "Victoria Sterling",
    email: "vsterling@sterlinglegal.com",
    phone: "+1-212-555-0164",
    riskScore: 0.11,
    ltv: 24000.0,
    amount: 1350.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "EXPIRED_CARD",
    code: "card_expired",
    caseStatus: "RECOVERED",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 1350.0,
    days: 15,
    notes: "Updated Amex details via billing portal. Recovered within 6 hours.",
  },
  {
    name: "Tariq Mansour",
    email: "tmansour@redsea-logistics.com",
    phone: "+20-2-2765-4321",
    riskScore: 0.58,
    ltv: 3100.0,
    amount: 240.0,
    gateway: "PADDLE",
    method: "CREDIT_CARD",
    reason: "RESTRICTED_CARD",
    code: "restricted_card",
    caseStatus: "ESCALATED",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 11,
    notes: "Corporate expense policy restricted online recurring charges. Support outreach in progress.",
  },
  {
    name: "Hannah Abbott",
    email: "hannah@greenleafhealth.org",
    phone: "+1-503-555-0144",
    riskScore: 0.27,
    ltv: 5400.0,
    amount: 430.0,
    gateway: "STRIPE",
    method: "ACH",
    reason: "ACH_RETURN_R03",
    code: "no_account_ach",
    caseStatus: "OPEN",
    priority: "URGENT",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "Bank account closed or number misentered. Urgent notice sent requesting new ACH mandate.",
  },
  {
    name: "Chen Wei",
    email: "chen.wei@hangzhou-cloud.cn",
    phone: "+86-571-8888-9999",
    riskScore: 0.33,
    ltv: 7800.0,
    amount: 580.0,
    gateway: "ADYEN",
    method: "CREDIT_CARD",
    reason: "GATEWAY_TIMEOUT",
    code: "gateway_timeout",
    caseStatus: "RECOVERED",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 580.0,
    days: 6,
    notes: "Cross-border latency caused gateway timeout. Instant retry settled successfully.",
  },
  {
    name: "Isabella Martinez",
    email: "imartinez@solardrive.es",
    phone: "+34-91-555-1234",
    riskScore: 0.39,
    ltv: 3600.0,
    amount: 310.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INSUFFICIENT_FUNDS",
    code: "insufficient_funds",
    caseStatus: "IN_PROGRESS",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 5,
    notes: "Customer confirmed funding account on Friday. Retry scheduled for 09:00 UTC Friday.",
  },
  {
    name: "Julian Thorne",
    email: "jthorne@thornebio.com",
    phone: "+1-858-555-0176",
    riskScore: 0.16,
    ltv: 16800.0,
    amount: 1150.0,
    gateway: "BRAINTREE",
    method: "CREDIT_CARD",
    reason: "CARD_DECLINED",
    code: "card_declined_generic",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 2,
    notes: "High-value enterprise tier payment decline. Priority recovery workflow initiated.",
  },
  {
    name: "Fatima Zahra",
    email: "fzahra@casablanca-fin.ma",
    phone: "+212-522-334455",
    riskScore: 0.62,
    ltv: 2200.0,
    amount: 165.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INCORRECT_PIN",
    code: "incorrect_pin",
    caseStatus: "FAILED",
    priority: "LOW",
    attempts: 4,
    recoveredAmount: 0.0,
    days: 25,
    notes: "Maximum automated dunning attempts reached with no response. Case closed as unrecoverable.",
  },
  {
    name: "Arthur Pendelton",
    email: "arthur@pendelton-consulting.com",
    phone: "+1-303-555-0129",
    riskScore: 0.24,
    ltv: 8400.0,
    amount: 720.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "PROCESSING_ERROR",
    code: "network_token_error",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 720.0,
    days: 10,
    notes: "Apple Pay network token re-synced. Payment captured.",
  },
];

// 15 Checkout Abandonment Scenarios
const checkoutAbandonmentsData = [
  {
    name: "Samantha Wright",
    email: "swright@wrightarch.com",
    phone: "+1-415-555-0211",
    riskScore: 0.2,
    ltv: 1500.0,
    amount: 299.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CART_ABANDONED_PAYMENT_STEP",
    code: "checkout_drop_payment_step",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "Customer entered payment details but dropped at 3DS verification. 1-hour cart recovery email sent.",
  },
  {
    name: "Benjamin Scott",
    email: "b.scott@scottmotors.com",
    phone: "+1-313-555-0195",
    riskScore: 0.3,
    ltv: 2400.0,
    amount: 450.0,
    gateway: "STRIPE",
    method: "APPLE_PAY",
    reason: "3DS_AUTHENTICATION_TIMEOUT",
    code: "three_ds_timeout",
    caseStatus: "IN_PROGRESS",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Biometric authentication timed out. Dynamic 1-click checkout recovery link sent via SMS.",
  },
  {
    name: "Camilla Lind",
    email: "camilla.lind@stockholmdesign.se",
    phone: "+46-8-555-0987",
    riskScore: 0.15,
    ltv: 3800.0,
    amount: 180.0,
    gateway: "ADYEN",
    method: "KLARNA",
    reason: "KLARNA_SESSION_EXPIRED",
    code: "session_timeout",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 180.0,
    days: 5,
    notes: "Klarna session re-activated via recovery email. Customer completed checkout.",
  },
  {
    name: "Derrick Hayes",
    email: "dhayes@hayeslogistics.com",
    phone: "+1-713-555-0167",
    riskScore: 0.45,
    ltv: 1200.0,
    amount: 520.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "ZIP_POSTAL_CODE_MISMATCH",
    code: "avs_mismatch",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "Billing address mismatch prevented order completion. Assisted checkout prompt sent.",
  },
  {
    name: "Zoe Kravitz-Ross",
    email: "zoe@soundwaveproductions.com",
    phone: "+1-323-555-0149",
    riskScore: 0.18,
    ltv: 4900.0,
    amount: 680.0,
    gateway: "BRAINTREE",
    method: "PAYPAL",
    reason: "PAYPAL_POPUP_CLOSED",
    code: "buyer_cancelled_paypal",
    caseStatus: "IN_PROGRESS",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 3,
    notes: "Customer closed PayPal popup prematurely. Follow-up discount incentive generated.",
  },
  {
    name: "Gabriel Dupont",
    email: "gabriel@lyon-biotech.fr",
    phone: "+33-4-72-11-22-33",
    riskScore: 0.22,
    ltv: 6200.0,
    amount: 350.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CURRENCY_CONVERSION_HESITATION",
    code: "cart_exit_pricing_page",
    caseStatus: "RECOVERED",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 350.0,
    days: 8,
    notes: "Presented local EUR pricing option via recovery campaign. Order converted.",
  },
  {
    name: "Ananya Iyer",
    email: "ananya.iyer@bangalore-ai.org",
    phone: "+91-80-4567-8901",
    riskScore: 0.25,
    ltv: 2900.0,
    amount: 210.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "OTP_NOT_RECEIVED",
    code: "bank_otp_timeout",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Bank SMS gateway delayed OTP. Email sent with saved cart and direct retry link.",
  },
  {
    name: "Travis Barker-Mills",
    email: "travis@austincreative.io",
    phone: "+1-512-555-0183",
    riskScore: 0.35,
    ltv: 1750.0,
    amount: 145.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CART_ABANDONED_SHIPPING_STEP",
    code: "abandoned_checkout_rates",
    caseStatus: "CLOSED",
    priority: "LOW",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 18,
    notes: "Cart expired after 14 days without conversion. Closed automatically.",
  },
  {
    name: "Leila Al-Sabah",
    email: "leila@kuwaitcapital.kw",
    phone: "+965-2244-5566",
    riskScore: 0.14,
    ltv: 8900.0,
    amount: 850.0,
    gateway: "ADYEN",
    method: "CREDIT_CARD",
    reason: "HIGH_VALUE_SECURITY_PROMPT",
    code: "step_up_auth_abandoned",
    caseStatus: "IN_PROGRESS",
    priority: "URGENT",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Corporate security challenge abandoned on checkout. High-touch VIP recovery assigned.",
  },
  {
    name: "Oliver Quinn",
    email: "oliver@quinndigital.co.nz",
    phone: "+64-9-555-0122",
    riskScore: 0.28,
    ltv: 3100.0,
    amount: 275.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CHECKOUT_FORM_ERROR",
    code: "client_side_validation_error",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 275.0,
    days: 6,
    notes: "Tax ID validation error resolved with pre-filled correct format link. Completed checkout.",
  },
  {
    name: "Nadia Popova",
    email: "nadia.popova@prague-ventures.cz",
    phone: "+420-221-555-678",
    riskScore: 0.32,
    ltv: 2200.0,
    amount: 195.0,
    gateway: "BRAINTREE",
    method: "PAYPAL",
    reason: "PAYPAL_AUTHENTICATION_FAILED",
    code: "paypal_auth_error",
    caseStatus: "OPEN",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "Cart saved with 48h price guarantee. Reminder email sent.",
  },
  {
    name: "Jason Ramirez",
    email: "jason@ramirez-agency.com",
    phone: "+1-305-555-0141",
    riskScore: 0.4,
    ltv: 3400.0,
    amount: 390.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "PAYMENT_METHOD_SELECTOR_EXIT",
    code: "abandoned_method_select",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 3,
    notes: "Visitor hesitated at payment method selection. Sent email offering invoice payment alternative.",
  },
  {
    name: "Yuki Takahashi",
    email: "yuki.t@osaka-robotics.jp",
    phone: "+81-6-5555-0112",
    riskScore: 0.17,
    ltv: 9500.0,
    amount: 720.0,
    gateway: "ADYEN",
    method: "CREDIT_CARD",
    reason: "3DS_CHALLENGE_TIMEOUT",
    code: "three_ds_challenge_abandoned",
    caseStatus: "RECOVERED",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 720.0,
    days: 7,
    notes: "Customer completed 3DS verification via second attempt on mobile app link.",
  },
  {
    name: "Clara Schumann",
    email: "clara@vienna-sound.at",
    phone: "+43-1-512-3456",
    riskScore: 0.26,
    ltv: 2600.0,
    amount: 160.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CART_ABANDONED_AT_SUMMARY",
    code: "summary_page_exit",
    caseStatus: "IN_PROGRESS",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 4,
    notes: "Left item in cart before clicking confirm. Automated recovery push notification sent.",
  },
  {
    name: "Maxwell Ford",
    email: "mford@fordconsulting.ca",
    phone: "+1-416-555-0190",
    riskScore: 0.21,
    ltv: 5800.0,
    amount: 490.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "INSUFFICIENT_CARD_LIMIT",
    code: "card_declined_limit",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "Card limit reached during bulk order checkout. Multi-card split payment option offered.",
  },
];

// 10 Failed Subscription Scenarios
const failedSubscriptionsData = [
  {
    name: "Acme Analytics Inc",
    email: "billing@acmeanalytics.com",
    phone: "+1-415-555-0301",
    riskScore: 0.15,
    ltv: 18000.0,
    amount: 499.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "RECURRING_BILLING_FAILED",
    code: "subscription_cycle_failed",
    caseStatus: "IN_PROGRESS",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 4,
    notes: "Pro tier monthly renewal failed. Smart dunning sequence day 4 with grace period warning.",
  },
  {
    name: "Vertex AI Labs",
    email: "finance@vertexlabs.ai",
    phone: "+1-650-555-0322",
    riskScore: 0.1,
    ltv: 36000.0,
    amount: 999.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CARD_EXPIRED_ON_RENEWAL",
    code: "card_expired_subscription",
    caseStatus: "OPEN",
    priority: "URGENT",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 2,
    notes: "Enterprise annual plan renewal. Card on file expired last month. Billing admin alert sent.",
  },
  {
    name: "Kester & Holt Media",
    email: "accounts@kesterholt.co.uk",
    phone: "+44-20-7946-0811",
    riskScore: 0.28,
    ltv: 6400.0,
    amount: 199.0,
    gateway: "PADDLE",
    method: "CREDIT_CARD",
    reason: "MANDATE_EXPIRED",
    code: "sepa_mandate_expired",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 3,
    notes: "Direct debit mandate renewal required under banking regulation. Sent re-authorization link.",
  },
  {
    name: "PulseHealth Technologies",
    email: "billing@pulsehealth.io",
    phone: "+1-617-555-0344",
    riskScore: 0.12,
    ltv: 28500.0,
    amount: 799.0,
    gateway: "STRIPE",
    method: "ACH",
    reason: "INSUFFICIENT_FUNDS_RECURRING",
    code: "ach_nsf_recurring",
    caseStatus: "RECOVERED",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 799.0,
    days: 10,
    notes: "Smart retry executed on scheduled payroll cycle (1st of month). Full renewal captured.",
  },
  {
    name: "Hyperion Cloud Solutions",
    email: "ap@hyperioncloud.de",
    phone: "+49-89-1234567",
    riskScore: 0.2,
    ltv: 14200.0,
    amount: 399.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "GENERIC_SUBSCRIPTION_DECLINE",
    code: "do_not_honor_recurring",
    caseStatus: "IN_PROGRESS",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 6,
    notes: "Bank decline on automated recurring charge. Customer requested temporary grace extension.",
  },
  {
    name: "Nordic Data Systems",
    email: "billing@nordicdata.fi",
    phone: "+358-9-123456",
    riskScore: 0.35,
    ltv: 5200.0,
    amount: 149.0,
    gateway: "ADYEN",
    method: "CREDIT_CARD",
    reason: "CARD_LOST_REPORTED",
    code: "stolen_card_subscription",
    caseStatus: "ESCALATED",
    priority: "HIGH",
    attempts: 3,
    recoveredAmount: 0.0,
    days: 14,
    notes: "Card cancelled due to corporate replacement. Multiple dunnings unread. Escalated to account manager.",
  },
  {
    name: "BrightSky Software",
    email: "pay@brightsky.com.au",
    phone: "+61-2-9876-5432",
    riskScore: 0.18,
    ltv: 9600.0,
    amount: 299.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "SPENDING_LIMIT_EXCEEDED",
    code: "balance_limit_recurring",
    caseStatus: "RECOVERED",
    priority: "LOW",
    attempts: 1,
    recoveredAmount: 299.0,
    days: 9,
    notes: "Corporate expense limit refreshed at month boundary. Automated smart retry recovered payment.",
  },
  {
    name: "Saffron Retail Tech",
    email: "finance@saffrontech.sg",
    phone: "+65-6789-0123",
    riskScore: 0.22,
    ltv: 11800.0,
    amount: 349.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "AUTHENTICATION_REQUIRED_RECURRING",
    code: "sca_authentication_required",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 1,
    notes: "PSD2/SCA regulation required off-session customer challenge. Magic authentication link sent.",
  },
  {
    name: "Apex Logistics SaaS",
    email: "billing@apexlog.io",
    phone: "+1-312-555-0377",
    riskScore: 0.42,
    ltv: 4800.0,
    amount: 129.0,
    gateway: "BRAINTREE",
    method: "CREDIT_CARD",
    reason: "INSUFFICIENT_FUNDS",
    code: "insufficient_funds_sub",
    caseStatus: "IN_PROGRESS",
    priority: "LOW",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 5,
    notes: "Starter tier renewal retry 2 of 4. Customer notified via email and in-app banner.",
  },
  {
    name: "OmniChannel Hub",
    email: "accounts@omnihub.co",
    phone: "+1-212-555-0388",
    riskScore: 0.16,
    ltv: 21000.0,
    amount: 599.0,
    gateway: "STRIPE",
    method: "CREDIT_CARD",
    reason: "CARD_EXPIRED",
    code: "expired_token",
    caseStatus: "RECOVERED",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 599.0,
    days: 11,
    notes: "Self-service billing portal update completed by CFO. Subscription restored to good standing.",
  },
];

// 10 Overdue Invoice Scenarios
const overdueInvoicesData = [
  {
    name: "Global Logistics Group Ltd",
    email: "invoices@globallogistics.com",
    phone: "+1-312-555-0401",
    riskScore: 0.25,
    ltv: 85000.0,
    amount: 6850.0,
    gateway: "STRIPE_INVOICING",
    method: "BANK_TRANSFER",
    reason: "NET_30_PAST_DUE",
    code: "invoice_net_30_overdue",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 15,
    notes: "Q3 platform licensing invoice INV-2026-089 is 15 days past Net-30 terms. Follow-up reminder dispatched.",
  },
  {
    name: "Atlas Heavy Industries",
    email: "ap-payables@atlasheavy.com",
    phone: "+1-412-555-0422",
    riskScore: 0.35,
    ltv: 145000.0,
    amount: 14200.0,
    gateway: "MANUAL_INVOICE",
    method: "WIRE",
    reason: "NET_60_PAST_DUE",
    code: "invoice_net_60_overdue",
    caseStatus: "ESCALATED",
    priority: "URGENT",
    attempts: 4,
    recoveredAmount: 0.0,
    days: 35,
    notes: "Enterprise contract annual maintenance payment overdue by 35 days. Legal & accounts payable escalation initiated.",
  },
  {
    name: "Crestview Healthcare Systems",
    email: "finance@crestviewhealth.org",
    phone: "+1-615-555-0433",
    riskScore: 0.15,
    ltv: 92000.0,
    amount: 8400.0,
    gateway: "STRIPE_INVOICING",
    method: "ACH",
    reason: "PURCHASE_ORDER_PENDING_APPROVAL",
    code: "po_approval_delay",
    caseStatus: "IN_PROGRESS",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 0.0,
    days: 12,
    notes: "Internal PO approval queue delay. Controller confirmed scheduled payment for upcoming check run.",
  },
  {
    name: "Valence BioPharma Corp",
    email: "payables@valencebio.com",
    phone: "+1-617-555-0455",
    riskScore: 0.12,
    ltv: 180000.0,
    amount: 12500.0,
    gateway: "STRIPE_INVOICING",
    method: "BANK_TRANSFER",
    reason: "INVOICE_UNMATCHED_REMITTANCE",
    code: "remittance_mismatch",
    caseStatus: "RECOVERED",
    priority: "HIGH",
    attempts: 2,
    recoveredAmount: 12500.0,
    days: 22,
    notes: "Remittance wire received without invoice reference. Matched and reconciled with accounting.",
  },
  {
    name: "Kodiak Energy Ventures",
    email: "accounting@kodiakenergy.ca",
    phone: "+1-403-555-0466",
    riskScore: 0.38,
    ltv: 62000.0,
    amount: 5400.0,
    gateway: "MANUAL_INVOICE",
    method: "ACH",
    reason: "NET_30_PAST_DUE",
    code: "invoice_net_30_overdue",
    caseStatus: "OPEN",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 8,
    notes: "First automated reminder sent for invoice INV-2026-104. Automated late notice email sent to AP.",
  },
  {
    name: "Starlight Digital Entertainment",
    email: "billing@starlightdigital.co.uk",
    phone: "+44-20-7946-0477",
    riskScore: 0.22,
    ltv: 44000.0,
    amount: 3750.0,
    gateway: "STRIPE_INVOICING",
    method: "CREDIT_CARD",
    reason: "INVOICE_AUTOPAY_FAILED",
    code: "invoice_card_declined",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 2,
    recoveredAmount: 3750.0,
    days: 14,
    notes: "Auto-pay card charge failed due to balance cap. Customer paid via instant ACH link.",
  },
  {
    name: "Pacific Rim Logistics Co",
    email: "ap@pacificrim-logistics.hk",
    phone: "+852-2555-0488",
    riskScore: 0.45,
    ltv: 53000.0,
    amount: 4900.0,
    gateway: "MANUAL_INVOICE",
    method: "WIRE",
    reason: "NET_45_PAST_DUE",
    code: "invoice_net_45_overdue",
    caseStatus: "IN_PROGRESS",
    priority: "HIGH",
    attempts: 3,
    recoveredAmount: 0.0,
    days: 20,
    notes: "Cross-border FX wire processing through intermediary bank. Tracking SWIFT MT103 confirmation.",
  },
  {
    name: "Beacon Cyber Security",
    email: "invoices@beaconsec.io",
    phone: "+1-703-555-0499",
    riskScore: 0.18,
    ltv: 110000.0,
    amount: 9800.0,
    gateway: "STRIPE_INVOICING",
    method: "ACH",
    reason: "ACCOUNT_PAYABLE_SYSTEM_MIGRATION",
    code: "vendor_portal_delay",
    caseStatus: "OPEN",
    priority: "HIGH",
    attempts: 1,
    recoveredAmount: 0.0,
    days: 7,
    notes: "Customer migrating to Coupa AP portal. Registered new vendor onboarding details to expedite invoice payment.",
  },
  {
    name: "Horizon Telecom Group",
    email: "ap-pay@horizontelecom.es",
    phone: "+34-91-555-0511",
    riskScore: 0.4,
    ltv: 72000.0,
    amount: 6100.0,
    gateway: "MANUAL_INVOICE",
    method: "BANK_TRANSFER",
    reason: "NET_60_PAST_DUE",
    code: "invoice_net_60_overdue",
    caseStatus: "ESCALATED",
    priority: "URGENT",
    attempts: 3,
    recoveredAmount: 0.0,
    days: 42,
    notes: "Invoice overdue by 42 days. Formal notice of suspension delivered to executive sponsors.",
  },
  {
    name: "Summit Ridge Properties",
    email: "finance@summitridgeprop.com",
    phone: "+1-303-555-0522",
    riskScore: 0.2,
    ltv: 58000.0,
    amount: 4200.0,
    gateway: "STRIPE_INVOICING",
    method: "ACH",
    reason: "NET_30_PAST_DUE",
    code: "invoice_net_30_overdue",
    caseStatus: "RECOVERED",
    priority: "MEDIUM",
    attempts: 1,
    recoveredAmount: 4200.0,
    days: 18,
    notes: "Payment released upon automated reminder with payment link. Full amount collected.",
  },
];

async function seed() {
  console.log("Starting database seed for RecoverAI...");

  // 1. Clean existing records in correct dependency order
  console.log("Cleaning up existing data...");
  await prisma.auditLog.deleteMany({});
  await prisma.recoveryAction.deleteMany({});
  await prisma.recoveryCase.deleteMany({});
  await prisma.transaction.deleteMany({});
  await prisma.customer.deleteMany({});

  console.log("Generating 60 synthetic recovery cases...");

  const allDatasets = [
    { type: "FAILED_PAYMENT", data: failedPaymentsData },
    { type: "CHECKOUT_ABANDONMENT", data: checkoutAbandonmentsData },
    { type: "FAILED_SUBSCRIPTION", data: failedSubscriptionsData },
    { type: "OVERDUE_INVOICE", data: overdueInvoicesData },
  ];

  let totalInserted = 0;
  let categoryCounts = {
    FAILED_PAYMENT: 0,
    CHECKOUT_ABANDONMENT: 0,
    FAILED_SUBSCRIPTION: 0,
    OVERDUE_INVOICE: 0,
  };

  for (const group of allDatasets) {
    for (const item of group.data) {
      const createdAt = daysAgo(item.days, Math.floor(Math.random() * 12));
      const resolvedAt = item.caseStatus === "RECOVERED" ? daysAgo(Math.max(0, item.days - 2)) : null;
      const nextRetryAt =
        item.caseStatus === "OPEN" || item.caseStatus === "IN_PROGRESS"
          ? new Date(Date.now() + (Math.floor(Math.random() * 48) + 12) * 3600 * 1000)
          : null;

      // 1. Customer
      const customer = await prisma.customer.create({
        data: {
          name: item.name,
          email: item.email,
          phone: item.phone,
          riskScore: item.riskScore,
          status: item.caseStatus === "FAILED" ? "AT_RISK" : "ACTIVE",
          lifetimeValue: item.ltv,
          currency: "USD",
          createdAt: daysAgo(item.days + 60),
        },
      });

      // 2. Transaction — with txnRef and transactionType
      const txnNumber = 10000 + totalInserted;
      const txnRef = `TXN-${txnNumber}`;
      const transaction = await prisma.transaction.create({
        data: {
          txnRef,
          customerId: customer.id,
          amount: item.amount,
          currency: "USD",
          transactionType: group.type,
          status: item.caseStatus === "RECOVERED" ? "SUCCEEDED" : "FAILED",
          paymentMethod: item.method,
          paymentGateway: item.gateway,
          failureReason: item.reason,
          failureCode: item.code,
          transactionDate: createdAt,
          createdAt: createdAt,
        },
      });

      // 3. Recovery Case — with caseRef
      const caseRef = `CASE-${txnNumber}`;
      const recoveryCase = await prisma.recoveryCase.create({
        data: {
          caseRef,
          customerId: customer.id,
          transactionId: transaction.id,
          status: item.caseStatus,
          priority: item.priority,
          recoveredAmount: item.recoveredAmount,
          attemptsCount: item.attempts,
          nextRetryAt: nextRetryAt,
          resolvedAt: resolvedAt,
          notes: item.notes,
          createdAt: createdAt,
        },
      });

      // 4. Recovery Actions
      const actionType =
        group.type === "CHECKOUT_ABANDONMENT"
          ? "PAYMENT_LINK"
          : group.type === "OVERDUE_INVOICE"
          ? "MANUAL_OUTREACH"
          : group.type === "FAILED_SUBSCRIPTION"
          ? "SMART_RETRY"
          : "EMAIL_DUNNING";

      const channel =
        group.type === "OVERDUE_INVOICE" ? "EMAIL" : group.type === "CHECKOUT_ABANDONMENT" ? "SMS" : "EMAIL";

      await prisma.recoveryAction.create({
        data: {
          recoveryCaseId: recoveryCase.id,
          actionType: actionType,
          channel: channel,
          status: item.caseStatus === "OPEN" ? "SCHEDULED" : "EXECUTED",
          scheduledAt: createdAt,
          executedAt: item.caseStatus !== "OPEN" ? daysAgo(Math.max(1, item.days - 1)) : null,
          result: item.caseStatus === "RECOVERED" ? "PAYMENT_UPDATED" : "DELIVERED",
          metadata: JSON.stringify({ category: group.type, attemptsMade: item.attempts }),
          createdAt: createdAt,
        },
      });

      // 5. Primary Audit Log — TRANSACTION_CREATED
      await prisma.auditLog.create({
        data: {
          entityType: "Transaction",
          entityId: transaction.id,
          action: "TRANSACTION_CREATED",
          actor: "SYSTEM",
          details: JSON.stringify({ txnRef, amount: item.amount, transactionType: group.type, status: "FAILED" }),
          customerId: customer.id,
          transactionId: transaction.id,
          createdAt: createdAt,
        },
      });

      // 5b. CASE_CREATED log
      await prisma.auditLog.create({
        data: {
          entityType: "RecoveryCase",
          entityId: recoveryCase.id,
          action: "CASE_CREATED",
          actor: "SYSTEM",
          details: JSON.stringify({
            caseRef,
            transactionRef: txnRef,
            category: group.type,
            amount: item.amount,
            reason: item.reason,
            initialPriority: item.priority,
          }),
          customerId: customer.id,
          recoveryCaseId: recoveryCase.id,
          transactionId: transaction.id,
          createdAt: new Date(createdAt.getTime() + 1000), // 1s after transaction
        },
      });

      // 5c. Recovery outcome log
      if (item.caseStatus === "RECOVERED") {
        await prisma.auditLog.create({
          data: {
            entityType: "RecoveryCase",
            entityId: recoveryCase.id,
            action: "PAYMENT_RECOVERED",
            actor: "SYSTEM",
            details: JSON.stringify({ recoveredAmount: item.recoveredAmount, txnRef, caseRef }),
            customerId: customer.id,
            recoveryCaseId: recoveryCase.id,
            transactionId: transaction.id,
            createdAt: resolvedAt ?? new Date(createdAt.getTime() + 48 * 3600 * 1000),
          },
        });
      }

      // 6. Secondary activity logs — outreach & retries
      const hoursAfterOpen = (h) => new Date(createdAt.getTime() + h * 3600 * 1000);

      // Email outreach for most cases
      if (["OPEN","IN_PROGRESS","ESCALATED","RECOVERED","FAILED"].includes(item.caseStatus)) {
        await prisma.auditLog.create({
          data: {
            entityType: "RecoveryCase",
            entityId: recoveryCase.id,
            action: "EMAIL_SENT",
            actor: "SYSTEM",
            details: JSON.stringify({ channel: "EMAIL", recipient: item.email, template: "dunning_v1" }),
            customerId: customer.id,
            recoveryCaseId: recoveryCase.id,
            transactionId: transaction.id,
            createdAt: hoursAfterOpen(2),
          },
        });
      }

      // SMS outreach for cases with phone & higher priority
      if (item.phone && ["URGENT","HIGH"].includes(item.priority) && item.attempts >= 1) {
        await prisma.auditLog.create({
          data: {
            entityType: "RecoveryCase",
            entityId: recoveryCase.id,
            action: "SMS_SENT",
            actor: "SYSTEM",
            details: JSON.stringify({ channel: "SMS", recipient: item.phone, template: "sms_alert_v1" }),
            customerId: customer.id,
            recoveryCaseId: recoveryCase.id,
            transactionId: transaction.id,
            createdAt: hoursAfterOpen(4),
          },
        });
      }

      // Retry failed for cases with 2+ attempts that are still open/escalated/failed
      if (item.attempts >= 2 && ["OPEN","ESCALATED","FAILED"].includes(item.caseStatus)) {
        await prisma.auditLog.create({
          data: {
            entityType: "RecoveryCase",
            entityId: recoveryCase.id,
            action: "RETRY_FAILED",
            actor: "SYSTEM",
            details: JSON.stringify({ attempt: item.attempts, failureReason: item.reason, gateway: item.gateway }),
            customerId: customer.id,
            recoveryCaseId: recoveryCase.id,
            transactionId: transaction.id,
            createdAt: hoursAfterOpen(24),
          },
        });
      }

      // Discount offered for cases with 3+ attempts still unresolved
      if (item.attempts >= 3 && ["OPEN","ESCALATED","IN_PROGRESS"].includes(item.caseStatus)) {
        await prisma.auditLog.create({
          data: {
            entityType: "RecoveryCase",
            entityId: recoveryCase.id,
            action: "DISCOUNT_OFFERED",
            actor: "AI_AGENT",
            details: JSON.stringify({ discountPercent: 15, promoCode: "RECOVER15", originalAmount: item.amount }),
            customerId: customer.id,
            recoveryCaseId: recoveryCase.id,
            transactionId: transaction.id,
            createdAt: hoursAfterOpen(36),
          },
        });
      }

      // Second email for recovered cases (confirmation)
      if (item.caseStatus === "RECOVERED") {
        await prisma.auditLog.create({
          data: {
            entityType: "RecoveryCase",
            entityId: recoveryCase.id,
            action: "EMAIL_SENT",
            actor: "SYSTEM",
            details: JSON.stringify({ channel: "EMAIL", recipient: item.email, template: "payment_confirmation" }),
            customerId: customer.id,
            recoveryCaseId: recoveryCase.id,
            transactionId: transaction.id,
            createdAt: hoursAfterOpen(6),
          },
        });
      }

      totalInserted++;
      categoryCounts[group.type]++;
    }
  }

  console.log("Database seed completed successfully!");
  console.log(`Total Cases Created: ${totalInserted}`);
  console.log(`- Failed Payments: ${categoryCounts.FAILED_PAYMENT}`);
  console.log(`- Checkout Abandonments: ${categoryCounts.CHECKOUT_ABANDONMENT}`);
  console.log(`- Failed Subscriptions: ${categoryCounts.FAILED_SUBSCRIPTION}`);
  console.log(`- Overdue Invoices: ${categoryCounts.OVERDUE_INVOICE}`);
}

seed()
  .catch((e) => {
    console.error("Error during seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
